In [2]:
import pandas as pd 
import numpy as np 
import yfinance as yf 

In [3]:
apple = yf.Ticker("AAPL")

In [60]:
data_raw = apple.history(start="2010-01-01",end = "2021-01-01")

In [61]:
data_raw.head()

Open      High       Low     Close     Volume  Dividends  \
Date                                                                       
2009-12-31  6.517775  6.524503  6.439181  6.444379  352410800        0.0   
2010-01-04  6.526951  6.559672  6.494840  6.544688  493729600        0.0   
2010-01-05  6.562730  6.593005  6.521445  6.556002  601904800        0.0   
2010-01-06  6.556002  6.581996  6.444992  6.451720  552160000        0.0   
2010-01-07  6.475573  6.483218  6.393003  6.439792  477131200        0.0   

            Stock Splits  
Date                      
2009-12-31           0.0  
2010-01-04           0.0  
2010-01-05           0.0  
2010-01-06           0.0  
2010-01-07           0.0

In [62]:
data_raw.shape

(2770, 7)

In [63]:
data_raw.describe()

Open         High          Low        Close        Volume  \
count  2770.000000  2770.000000  2770.000000  2770.000000  2.770000e+03   
mean     31.860089    32.192432    31.528051    31.873388  2.866399e+08   
std      24.853383    25.189297    24.510128    24.864564  2.289079e+08   
min       5.882908     5.993918     5.818078     5.873124  4.544800e+07   
25%      15.302909    15.481825    15.195131    15.346518  1.211217e+08   
50%      24.857037    25.113631    24.569914    24.791559  2.030340e+08   
75%      41.326665    41.681166    41.071286    41.346444  3.889732e+08   
max     137.029580   137.764100   133.346996   135.679626  1.880998e+09   

         Dividends  Stock Splits  
count  2770.000000   2770.000000  
mean      0.001814      0.003971  
std       0.016741      0.153161  
min       0.000000      0.000000  
25%       0.000000      0.000000  
50%       0.000000      0.000000  
75%       0.000000      0.000000  
max       0.205000      7.000000

In [64]:
data_raw.isnull().any()

Open            False
High            False
Low             False
Close           False
Volume          False
Dividends       False
Stock Splits    False
dtype: bool

In [65]:
data_prepared["Target"] = 0

In [66]:
data_prepared = data_raw.copy(deep=True)

In [67]:
data_prepared["Target"] = data_prepared["Open"] < data_prepared["Close"]


In [68]:
data_prepared["Target"] = data_prepared["Target"].astype(int)

In [69]:
data_prepared["Target"].value_counts()

1    1439
0    1331
Name: Target, dtype: int64

In [70]:
data_prepared["close-open"] = data_prepared["Close"] - data_prepared["Open"]

In [72]:
data_prepared["Target"] = data_prepared["Target"].shift(-1)

In [73]:
data_prepared.tail()

Open        High         Low       Close     Volume  \
Date                                                                    
2020-12-24  130.349333  132.473514  130.130958  130.994522   54930100   
2020-12-28  132.999587  136.324816  132.523124  135.679626  124486200   
2020-12-29  137.029580  137.764100  133.346996  133.873077  121047300   
2020-12-30  134.577850  134.984823  132.413956  132.731598   96452100   
2020-12-31  133.088938  133.744064  130.746382  131.709213   99116600   

            Dividends  Stock Splits  Target  close-open  
Date                                                     
2020-12-24        0.0           0.0     1.0    0.645189  
2020-12-28        0.0           0.0     0.0    2.680039  
2020-12-29        0.0           0.0     0.0   -3.156502  
2020-12-30        0.0           0.0     0.0   -1.846252  
2020-12-31        0.0           0.0     NaN   -1.379725

In [76]:
pip install sklearn

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=ff699bf64a0122ce91e855279bed6cc2b0fe058b75b7205ca0d006e687942059
  Stored in directory: c:\users\91976\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn


You should consider upgrading via the 'C:\Users\91976\AppData\Local\Programs\Python\Python38-32\python.exe -m pip install --upgrade pip' command.


In [77]:
from sklearn.linear_model import LogisticRegression

In [78]:
data_prepared.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'Target', 'close-open'],
      dtype='object')

In [104]:
attrs = ['close-open']
target = ["Target"]

In [107]:
x_train, y_train, x_test, y_test = data_prepared[attrs][:2700], data_prepared[target][:2700], data_prepared[attrs][2700:], data_prepared[target][2700:]

In [108]:
x_train

close-open
Date                  
2009-12-31   -0.073395
2010-01-04    0.017737
2010-01-05   -0.006728
2010-01-06   -0.104282
2010-01-07   -0.035780
...                ...
2020-09-16   -3.071792
2020-09-17    0.614352
2020-09-18   -3.527605
2020-09-21    5.489580
2020-09-22   -0.862085

[2700 rows x 1 columns]

In [109]:
LR = LogisticRegression()

In [110]:
LR.fit(x_train,y_train)

C:\Users\91976\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [111]:
y_test_pred = LR.predict(x_test)

In [112]:
y_pred_train = LR.predict(x_train)

In [113]:
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report

In [114]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

         0.0       0.53      0.14      0.22      1299
         1.0       0.53      0.89      0.66      1401

    accuracy                           0.53      2700
   macro avg       0.53      0.51      0.44      2700
weighted avg       0.53      0.53      0.45      2700



In [115]:
y_pred_train

array([1., 1., 1., ..., 1., 0., 1.])

In [116]:
LR.coef_

array([[-0.22291519]])

In [117]:
LR.intercept_

array([0.07888155])

In [120]:
print(classification_report(y_test[:-1], y_test_pred[:-1]))

              precision    recall  f1-score   support

         0.0       0.50      0.52      0.51        31
         1.0       0.59      0.58      0.59        38

    accuracy                           0.55        69
   macro avg       0.55      0.55      0.55        69
weighted avg       0.55      0.55      0.55        69

